"use strict";
/* jlTimer UI look (draft): Bento. Dashboard / bento-grid tiles like iOS widgets: the button bar, scramble,
   session row, current/best summary and solve list each sit in their own soft rounded tile with gaps between them.
   Tile color is derived from the inherited text color (light tile under dark text, dark tile under light text), so
   the theme/kernel palette keeps tinting it. */
jlSkins.register({ id: 'bento', name: 'Bento', css: [
	// ---- tokens ----
	'html.jls-bento {',
	'	--bt-g: 0.75rem;',
	'	--bt-r: 1.25rem;',
	'	--bt-rs: 0.8rem;',
	'	--bt-lw: 16rem;',
	'	--bt-lh: 12.6rem;',
	'	--bt-font: -apple-system, BlinkMacSystemFont, "SF Pro Display", "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;',
	'	--bt-tile: rgba(255, 255, 255, 0.86);',
	'	--bt-tile-hi: rgba(255, 255, 255, 0.95);',
	'	--bt-well: rgba(127, 127, 127, 0.1);',
	'	--bt-line: rgba(127, 127, 127, 0.16);',
	'	--bt-shadow: 0 0.1rem 0.25rem rgba(0, 0, 0, 0.06), 0 0.5rem 1.6rem rgba(0, 0, 0, 0.1);',
	'}',
	'@supports (color: rgb(from currentColor r g b)) {',
	// any element using these resolves currentColor to its own text color: dark text -> near-white tile, light text -> near-black tile
	'	html.jls-bento {',
	'		--bt-tile: rgb(from currentColor calc(clamp(16, (150 - (r + g + b) / 3) * 8, 252) * 0.94 + r * 0.06) calc(clamp(16, (150 - (r + g + b) / 3) * 8, 252) * 0.94 + g * 0.06) calc(clamp(16, (150 - (r + g + b) / 3) * 8, 252) * 0.94 + b * 0.06) / 0.86);',
	'		--bt-tile-hi: rgb(from currentColor calc(clamp(22, (150 - (r + g + b) / 3) * 8, 254) * 0.96 + r * 0.04) calc(clamp(22, (150 - (r + g + b) / 3) * 8, 254) * 0.96 + g * 0.04) calc(clamp(22, (150 - (r + g + b) / 3) * 8, 254) * 0.96 + b * 0.04) / 0.95);',
	'		--bt-well: rgb(from currentColor r g b / 0.07);',
	'		--bt-line: rgb(from currentColor r g b / 0.12);',
	'	}',
	'}',

	// ---- shared tile surface ----
	'html.jls-bento #leftbar,',
	'html.jls-bento #scrambleDiv.mywindow,',
	'html.jls-bento #toolsDiv.mywindow,',
	'html.jls-bento #stats > div,',
	'html.jls-bento .mywindow:not(.fixed):not(#stats) {',
	'	background-color: var(--bt-tile) !important;',
	'	border: 0 !important;',
	'	border-radius: var(--bt-r) !important;',
	'	box-shadow: var(--bt-shadow) !important;',
	'}',
	'html.jls-bento .mywindow:not(.fixed)::before, html.jls-bento #leftbar::before {',
	'	display: none;',
	'}',
	'html.jls-bento .mywindow, html.jls-bento #leftbar > div, html.jls-bento #avgstr, html.jls-bento .dialog, html.jls-bento .popup {',
	'	font-family: var(--bt-font) !important;',
	'}',
	'html.jls-bento .mywindow > .chide {',
	'	width: 0.9rem; height: 0.9rem; top: 0.45rem; left: 0.45rem;',
	'	border-radius: 50%;',
	'	background-color: var(--bt-line);',
	'}',

	// ---- button bar: a tile with rounded key caps ----
	'html.jls-bento:not(.m) #leftbar {',
	'	left: var(--bt-g); top: var(--bt-g);',
	'	width: var(--bt-lw); height: var(--bt-lh);',
	'	padding: 0;',
	'}',
	'html.jls-bento #leftbar > div.mybutton {',
	'	border: 0.28rem solid transparent !important;',
	'	background-clip: padding-box;',
	'	border-radius: calc(var(--bt-rs) + 0.28rem);',
	'	transition: background-color 0.15s;',
	'}',
	'html.jls-bento #leftbar > div.mybutton:not(#logo) { background-color: transparent; }',
	'html.jls-bento:not(.m) #leftbar > div.mybutton:not(#logo):hover {',
	'	background-color: var(--bt-well) !important;',
	'}',
	'html.jls-bento #leftbar > div.mybutton.enable:not(#logo) {',
	'	background-color: var(--bt-well) !important;',
	'}',
	'html.jls-bento:not(.m) #leftbar > div.c1, html.jls-bento:not(.m) #leftbar > div.c2, html.jls-bento:not(.m) #leftbar > div.c3 { border-bottom-width: 0.14rem !important; margin-top: 0.3rem; }',
	'html.jls-bento:not(.m) #leftbar > div.c4, html.jls-bento:not(.m) #leftbar > div.c5, html.jls-bento:not(.m) #leftbar > div.c6 { border-top-width: 0.14rem !important; margin-top: -0.3rem; }',
	'html.jls-bento:not(.m) #leftbar > div.c1, html.jls-bento:not(.m) #leftbar > div.c4 { margin-left: 0.3rem; }',
	'html.jls-bento:not(.m) #leftbar > div.c3, html.jls-bento:not(.m) #leftbar > div.c6 { margin-right: 0.3rem; }',
	'html.jls-bento:not(.m) #leftbar > #logo { width: auto; left: 0.3rem; right: 0.3rem; }',
	'html.jls-bento #leftbar #logo {',
	'	font-family: var(--bt-font) !important;',
	'	font-weight: 800;',
	'	letter-spacing: -0.03em;',
	'	font-size: 2.7em;',
	'	box-shadow: none !important;',
	'}',
	'html.jls-bento #leftbar .mybutton .icon::before {',
	'	width: 2rem; height: 2rem;',
	'}',

	// ---- scramble tile ----
	'html.jls-bento:not(.m) #scrambleDiv {',
	'	top: var(--bt-g); right: var(--bt-g);',
	'	left: calc(var(--bt-lw) + var(--bt-g) * 2);',
	'}',
	'html.jls-bento #scrambleDiv {',
	'	padding: 0.55rem 1.2rem 0.6rem;',
	'}',
	'html.jls-bento #scrambleDiv > .title { margin-bottom: 0.35rem; }',
	'html.jls-bento #scrambleTxt {',
	'	font-weight: 600;',
	'	letter-spacing: 0.3rem;',
	'	line-height: 1.35;',
	'	padding: 0.2rem 0.4rem;',
	'}',

	// ---- form controls: soft pills ----
	'html.jls-bento select, html.jls-bento input[type="button"], html.jls-bento input[type="text"] {',
	'	background-color: var(--bt-well) !important;',
	'	border: 0 !important;',
	'	border-radius: 999px;',
	'	padding: 0.35rem 0.85rem;',
	'	font-weight: 600;',
	'	color: inherit;',
	'}',
	'html.jls-bento select, html.jls-bento input[type="button"]:not(.icon), html.jls-bento input[type="text"] { font-family: var(--bt-font); }',
	'html.jls-bento input[type="button"]:hover, html.jls-bento select:hover { background-color: var(--bt-line) !important; }',
	'html.jls-bento input.icon[type="button"] { padding: 0.35rem 0.6rem; }',
	'html.jls-bento .click { border-radius: 0.4em; }',

	// ---- stats: the window disappears, its three parts become tiles ----
	'html.jls-bento #stats.mywindow {',
	'	background: transparent !important;',
	'	box-shadow: none !important;',
	'	border: 0 !important;',
	'	-webkit-backdrop-filter: none !important; backdrop-filter: none !important;',
	'	padding: 0;',
	'}',
	'html.jls-bento:not(.m) #stats {',
	'	left: var(--bt-g); bottom: var(--bt-g);',
	'	top: calc(var(--bt-lh) + var(--bt-g) * 2);',
	'	min-width: var(--bt-lw);',
	'}',
	'html.jls-bento:not(.m) #stats:not([style*="none"]) {',
	'	display: flex !important;',
	'	flex-direction: column;',
	'	gap: var(--bt-g);',
	'}',
	'html.jls-bento #stats > div {',
	'	-webkit-backdrop-filter: blur(10px) saturate(1.2);',
	'	backdrop-filter: blur(10px) saturate(1.2);',
	'	margin: 0 !important;',
	'}',
	'html.jls-bento #stats > div:first-child {',
	'	padding: 0.55rem 0.6rem 0.55rem 1.6rem;',
	'	display: flex; align-items: center; gap: 0.4rem;',
	'	text-align: left;',
	'}',
	'html.jls-bento #stats > div:first-child > .click {',
	'	flex: 1;',
	'	font-size: 0.72rem; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase;',
	'	opacity: 0.75;',
	'}',
	'html.jls-bento #stats > div:first-child select { flex: 0 1 6rem; min-width: 0; margin: 0; }',
	'html.jls-bento #stats > div:first-child input { margin: 0; }',
	'html.jls-bento #stats .statc { padding: 0.75rem 0.7rem 0.85rem; width: auto; }',
	'html.jls-bento:not(.m) #stats .stattl {',
	'	flex: 1 1 auto; min-height: 0;',
	'	display: flex; flex-direction: column;',
	'	padding: 0.35rem 0.5rem;',
	'	overflow: hidden;',
	'}',
	'html.jls-bento:not(.m) #stats .stattl > .myscroll {',
	'	flex: 1 1 auto; min-height: 0;',
	'	height: auto !important;',
	'}',
	'html.jls-bento #stats table { font-variant-numeric: tabular-nums; }',
	'html.jls-bento #stats .table, html.jls-bento #stats .table td, html.jls-bento #stats .table th {',
	'	border: 0 !important;',
	'}',
	// summary table: small uppercase labels, big numbers
	'html.jls-bento #stats table.sumtable { border-collapse: separate; border-spacing: 0; }',
	'html.jls-bento #stats table.sumtable th {',
	'	font-size: 0.68rem; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase;',
	'	opacity: 0.6;',
	'	padding: 0.15rem 0.4rem !important;',
	'	text-align: left;',
	'}',
	'html.jls-bento #stats table.sumtable tr:first-child th { text-align: right; padding-bottom: 0.25rem !important; }',
	'html.jls-bento #stats table.sumtable td {',
	'	font-size: 1.55rem; font-weight: 750; letter-spacing: -0.02em;',
	'	text-align: right;',
	'	padding: 0.1rem 0.4rem !important;',
	'	line-height: 1.15;',
	'}',
	'html.jls-bento #stats table.sumtable td[data^="b"] { color: inherit; }',
	// solve list
	'html.jls-bento #stats .stattl .table { width: 100%; border-collapse: separate; border-spacing: 0; }',
	'html.jls-bento #stats .stattl .table th {',
	'	font-size: 0.68rem; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase;',
	'	padding: 0.45rem 0.3rem !important;',
	'}',
	'html.jls-bento #stats .stattl .table tr:nth-child(2) th { opacity: 0.6; border-bottom: 1px solid var(--bt-line) !important; }',
	'html.jls-bento #stats .stattl .table tr:first-child th {',
	'	font-size: 0.95rem; font-weight: 750; letter-spacing: 0; text-transform: none;',
	'	line-height: 1.3; padding: 0.55rem 0.3rem 0.5rem !important;',
	'	opacity: 1;',
	'}',
	'html.jls-bento #stats .stattl .table td {',
	'	padding: 0.42rem 0.3rem !important;',
	'	font-weight: 600;',
	'	border-bottom: 1px solid var(--bt-line) !important;',
	'}',
	'html.jls-bento #stats .stattl .table tr:last-child td { border-bottom: 0 !important; }',
	'html.jls-bento #stats .stattl .table td:first-child { opacity: 0.5; font-weight: 500; font-size: 0.85em; }',
	'html.jls-bento #stats .times.pb { font-weight: 800; }',

	// ---- ao5 / ao12 under the timer: little stat tiles ----
	'html.jls-bento #avgstr { text-shadow: none !important; line-height: 1 !important; }',
	'html.jls-bento #avgstr > br { display: none; }',
	'html.jls-bento #avgstr > span {',
	'	background-color: var(--bt-tile);',
	'	box-shadow: var(--bt-shadow);',
	'	border-radius: 0.38em;',
	'	padding: 0.32em 0.6em 0.36em;',
	'	margin: 0.25em 0.14em 0;',
	'	font-weight: 750;',
	'	letter-spacing: -0.01em;',
	'	font-variant-numeric: tabular-nums;',
	'	text-transform: uppercase;',
	'}',
	'html.jls-bento #container > #avgstr { font-size: 0.115em; }',
	'html.jls-bento #multiphase > #avgstr { font-size: 0.2em; }',
	'html.jls-bento #multiphase > #avgstr > span { display: block; width: max-content; margin: 0.3em 0 0 auto; }',
	'html.jls-bento:not(.m) #avgstr .click:hover { background-color: var(--bt-tile-hi) !important; }',

	// ---- dialogs and popups ----
	'html.jls-bento .dialog, html.jls-bento .popup {',
	'	background-color: var(--bt-tile-hi) !important;',
	'	border: 0 !important;',
	'	border-radius: 1.4rem !important;',
	'	box-shadow: 0 0.3rem 0.8rem rgba(0, 0, 0, 0.08), 0 1.4rem 3.5rem rgba(0, 0, 0, 0.22) !important;',
	'	padding: 0.9rem;',
	'}',
	'html.jls-bento .dialog .title { font-weight: 800; letter-spacing: 0.08em; text-transform: uppercase; font-size: 0.95em; }',
	'html.jls-bento .tab {',
	'	border: 0 !important;',
	'	border-radius: 0.75rem !important;',
	'	padding: 0.5rem 0.7rem !important;',
	'	font-weight: 600;',
	'	background-color: transparent;',
	'}',
	'html.jls-bento .tab.enable { background-color: var(--bt-well) !important; font-weight: 800; }',
	'html.jls-bento:not(.m) .tab:hover { background-color: var(--bt-well) !important; }',
	'html.jls-bento .tabValue {',
	'	border: 0 !important;',
	'	border-radius: 1rem;',
	'	background-color: var(--bt-well);',
	'}',
	'html.jls-bento table.opttable tr th:first-child {',
	'	border-radius: 0.8rem;',
	'}',
	'html.jls-bento table.opttable tr:nth-child(odd) td:first-child { background: transparent !important; }',
	'html.jls-bento table.opttable td { border-bottom: 1px solid var(--bt-line); }',
	'html.jls-bento .dialog input.buttonOK, html.jls-bento .dialog .button input[type="button"] {',
	'	padding: 0.45rem 1.2rem;',
	'}',
	'html.jls-bento textarea { border-radius: 0.8rem; border: 0; }',

	// ---- jlTimer minimal layout (jlmin): panels without frames, as in the base design ----
	'html.jls-bento.jlmin #leftbar, html.jls-bento.jlmin .mywindow:not(.fixed):not(#stats), html.jls-bento.jlmin #stats > div, html.jls-bento.jlmin #avgstr > span {',
	'	background-color: transparent !important;',
	'	box-shadow: none !important;',
	'	-webkit-backdrop-filter: none !important; backdrop-filter: none !important;',
	'}',

	// ---- bottom-bar layout (.m) and phones ----
	'html.jls-bento.m #leftbar {',
	'	left: var(--bt-g); right: var(--bt-g); bottom: var(--bt-g);',
	'	border-radius: var(--bt-r) !important;',
	'}',
	'html.jls-bento.m #leftbar > div.mybutton { border-width: 0.22rem !important; }',
	'html.jls-bento.m #leftbar #logo { font-size: 2.3em; }',
	'html.jls-bento.m #stats {',
	'	left: var(--bt-g); right: var(--bt-g);',
	'	bottom: calc(11.8vw + var(--bt-g) * 2);',
	'	max-width: calc(100% - var(--bt-g) * 2);',
	'	box-sizing: border-box;',
	'	text-align: center;',
	'}',
	'html.jls-bento.m #stats > div:first-child { display: flex; margin-bottom: var(--bt-g) !important; justify-content: center; }',
	'html.jls-bento.m #stats > div:first-child > .click { flex: 0 0 auto; }',
	'html.jls-bento.m #stats .statc { margin-right: var(--bt-g) !important; padding: 0.5rem; }',
	'html.jls-bento.m #stats .stattl { padding: 0.3rem 0.4rem; vertical-align: top; }',
	'html.jls-bento.m #toolsDiv { bottom: calc(11.8vw + var(--bt-g) * 2); right: var(--bt-g); }',
	'html.jls-bento.m #scrambleDiv {',
	'	left: var(--bt-g); right: var(--bt-g); top: var(--bt-g);',
	'	width: auto;',
	'}'
].join('\n') });
